ASPNETCourse/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPNETCourse.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Labs()
        {
            ViewBag.Message = "Hand On Labs";

            return View();
        }

        public ActionResult Lectures()
        {
            ViewBag.Message = "Lectures";

            return View();
        }
    }
}

ASPNETCourse/Controllers/LabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPNETCourse.Controllers
{
    public class LabsController : Controller
    {
        public ActionResult Lab1()
        {
            return View();
        }

        public ActionResult Lab2()
        {
            return View();
        }

        public ActionResult Lab3()
        {
            return View();
        }

        public ActionResult Lab4()
        {
            return View();
        }

        public ActionResult Lab5()
        {
            return View();
        }

        public ActionResult Lab6()
        {
            return View();
        }

        public ActionResult Lab7()
        {
            return View();
        }

        public ActionResult Lab8()
        {
            return View();
        }

        public ActionResult Lab9()
        {
            return View();
        }

        public ActionResult Lab10_11()
        {
            return View();
        }

        public ActionResult Lab12()
        {
            return View();
        }

        public ActionResult Lab13()
        {
            return View();
        }

        public ActionResult Lab14_15()
        {
            return View();
        }
    }
}

ASPNETCourse/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>What is Cloud Computing?</h1>
    <p class="lead"> What is Cloud Computing? One of examples is Microsoft Azure, in short, it’s Microsoft’s cloud platform a growing collection of integrated services—compute, storage, data, networking, and app—that help you move faster, do more, and save money. But that’s just scratching the surface. here’s what else azure is….</p>
    <p><a href="http://azure.microsoft.com/en-us/" class="btn btn-primary btn-lg" target="_blank">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="myrow">
        <h2>It’s IaaS + PaaS</h2>
        <p>
            Azure is the only major cloud platform ranked by Gartner as an industry leader for both infrastructure-as-a-service (IaaS) and platform-as-a-service (PaaS). This powerful combination of managed and unmanaged services lets you build, deploy, and manage applications any way you like for unmatched productivity.
        </p>
        <hr/>
    </div>
    <div class="myrow">
        <h2>It’s hybrid ready</h2>
        <p>Some cloud providers make you choose between your datacenter and the public cloud. Not Azure. Its enterprise-proven hybrid cloud solutions give you the best of both worlds, expanding your IT options without added complexity. With Azure, data storage, backup, and recovery become more efficient and economical. It’s also easier to build applications that span both on-premises and the cloud.</p>
        <hr />
    </div>
    <div class="myrow">
        <h2>It’s open and flexible</h2>
        <p>Azure supports any operating system, language, tool, and framework— from Windows to Linux, SQL Server to Oracle, C# to Java. It puts the best of Windows and Linux ecosystems at your fingertips, so you can build great applications and services that work with every device.</p>
        <hr />
    </div>
    <div class="myrow">
        <h2>It’s always up, always on</h2>
        <p>You’ll share the same enterprise-tested platform that powers Skype, Office 365, Bing, and Xbox. Azure offers a 99.95% availability SLA, 24x7 tech support, and round-the-clock service health monitoring. That’s why more than 57% of Fortune 500 companies rely on Azure today. From live streaming Olympic events to online multiplayer online games, our customers are doing some amazing things.</p>
        <hr />
    </div>
    <div class="myrow">
        <h2>It’s economical and scalable</h2>
        <p>Azure can quickly scale up or down to match demand, so you only pay for what you use. Per-minute billing and a commitment to match competitor prices for popular infrastructure services like compute, storage and bandwidth means you’re always getting unbeatable price for performance.</p>
        <hr />
    </div>
    <div class="myrow">
        <h2>It’s everywhere</h2>
        <p>Azure runs on a growing global network of Microsoft-managed datacenters across 19 regions, giving you a wide range of options for running applications and ensuring your customers always get great performance. Azure is the first multinational cloud provider in mainland China and is continuing to expand to new regions around the globe</p>
        
    </div>
</div>
<style>
    .myrow {
        margin-left: 5em; 
        margin-right: 5em; 
    }
</style>

ASPNETCourse/Views/Home/Labs.cshtml
@{
    ViewBag.Title = "Hand On Labs";
}
<h2>@ViewBag.Title</h2>

<section class="content">
    <p>
        The Training Kit includes step-by-step hands-on labs designed to help you improve you Microsoft Azure skills. You can browse through the complete list of hands-on lab below. To get started with a hands-on lab, simply install the necessary prerequisites and follow the setup procedures described for each lab.
    </p>
    <ul class="list-group">
        <li class="list-group-item">
            <a name="Lab1"></a>
            <h3>Lab 1. Getting Started with the Azure Preview Portal</h3>
            <p>The new Azure Preview portal is an all-in-one, work-anywhere experience. Now you can manage websites, databases, and Visual Studio Online team projects in a reimagined UX personalized to your work style. In this Hands-on lab, you will learn how to create a new resource group by building a Website and a SQL Server, and set up continuous deployment using Team Project</p>
            <ul class="links">
                <li>@Html.ActionLink("Lab Manual", "Lab1", "Labs")</li>
                @*<li><a href="\Labs\MVC4Fundamentals\Source.zip">Lab Files</a></li>*@
            </ul>
        </li>
        <li class="list-group-item">
            <a name="Lab2"></a>
            <h3>Lab 2. Building and Publishing ASP.NET Applications with Windows Azure Web Sites</h3>
            <p>In this hands-on lab, you will explore the basic elements of the Windows Azure Web Sites service by creating a simple ASP.NET MVC 5 application, which uses scaffolding to automatically generate the baseline of your application's CRUD (Create, Read, Update and Delete). Then, you will deploy it using Web Deploy from Microsoft Visual Studio and finally, you will enable source control and use Git to publish directly from your local computer</p>
            <ul class="links">
                <li>@Html.ActionLink("Lab Manual", "Lab2", "Labs")</li>
                <li><a href="\Sources\Lab2\Source.zip">Lab Files</a></li>
            </ul>
        </li>
    </ul>
    <div class="topOfPage"><a href="#top">Top of page</a></div>
</section>

ASPNETCourse/Views/Home/Lectures.cshtml
@{
    ViewBag.Title = "Lectures";
}
<h2>@ViewBag.Title.</h2>

<div class="row">
    <div class="col-md-4">
        <p>Lecture 1. Introduction</p>
        <iframe src="https://onedrive.live.com/embed?cid=40A7EF59EE3E4A15&resid=40A7EF59EE3E4A15%21778216&authkey=AOEt_umykO4ub-4&em=2" width="402" height="327" frameborder="0" scrolling="no"></iframe>
    </div>
</div>